function [jw_svi_mod] = makeSviModelJW(ts_, v_ts_, psi_ts_, p_ts_, c_ts_, ...
    v_tilde_ts_)
% Function to build SVI JW parametrization
% In
%   ts_ [vector]: Vector of tenors
%   v_ts_ [vector]: ATM variance
%   psi_ts_ [vector]: ATM skew
%   p_ts_ [vector]: Slope of the left (put) wing;
%   c_ts_ [vector]: Slope of the right (call) wing;
%   v_tilde_ts_ [vector]: Minimum implied variance
% Out
%   jw_svi_mod [struct]: SVI JW parametrization

jw_svi_mod = struct(...
    'ts', ts_, ...
    'v_ts', v_ts_, ...
    'psi_ts', psi_ts_, ...
    'p_ts', p_ts_, ...
    'c_ts', c_ts_, ...
    'v_tilde_ts', v_tilde_ts_);

end
